name: fitcel
description: A fitness app with workout and diet plans of Celebrities.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  card_swiper : ^2.0.4
  firebase_core : ^2.9.0
  firebase_auth: ^4.4.1
  page_transition: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
      - assets/images/

  fonts:
    - family: Montserrat
      fonts:
      - asset: assets/fonts/Montserrat[wght].ttf
      - asset: assets/fonts/Montserrat-Italic[wght].ttf
        style: italic